FORMAT: 1A

# Edukt

Edukt es una API para proveer de datos a las aplicaciones moviles y web de Edukt

## Estudiantes [/api/v1/student]

### Registro del estudiante [POST]
+ Response 201 (application/json)

          {
            "dni_students": "1014563233",
            "name": "Jhoan",
            "lastname": "Cuartas higuita",
            "birthday": "1999-10-10T05:30:00.175Z",
            "degree": "Ingeniero",
            "email": "cuartas@gmail.com",
            "password": "edea791aa9bd3f2c7d9d2f4a6b313d938133a4ffb3278a9c32ef0e814c276970",
            "updatedAt": "2018-09-30T20:59:49.005Z",
            "createdAt": "2018-09-30T20:59:49.005Z"
          }



